[package]
name = "oha"
version = "0.5.1"
authors = ["hatoo <hato2000@gmail.com>"]
edition = "2021"
description = "Ohayou(おはよう), HTTP load generator, inspired by rakyll/hey with tui animation."
repository = "https://github.com/hatoo/oha"
readme = "README.md"
keywords = ["cli", "load-testing", "performance", "http"]
categories = ["command-line-utilities", "network-programming", "web-programming::http-client", "development-tools::profiling"]
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
default = ["native-tls"]
native-tls = ["dep:native-tls", "dep:tokio-native-tls"]
rustls = ["dep:rustls", "dep:tokio-rustls", "dep:rustls-native-certs"]

[dependencies]
clap = { version = "3.0.0", features = ["derive"] }
tokio = { version = "1.14.0", features = ["full"] }
anyhow = "1.0.38"
thiserror = "1.0.16"
futures = "0.3.12"
average = "0.13.0"
float-ord = "0.3.1"
byte-unit = "4.0.8"
tui = { version = "0.17.0", default-features = false, features = ["crossterm"] }
crossterm = "0.22.0"
libc = "0.2.67"
flume = "0.10"
humantime = "2.0.0"

hyper = { version = "0.14.13", features = ["full"] }
http = "0.2"

# native-tls
native-tls = { version = "0.2.4", optional = true }
tokio-native-tls = { version = "0.3.0", optional = true }

# rustls
rustls = { version = "0.20.4", features = ["dangerous_configuration"], optional = true }
tokio-rustls = { version = "0.23.3", optional = true }
rustls-native-certs = { version = "0.6.2", optional = true }

rand = "0.8"
trust-dns-resolver = "0.21.1"
base64 = "0.13.0"
lazy_static = "1.4.0"

[target.'cfg(unix)'.dependencies]
rlimit = "0.7.0"

[dev-dependencies]
assert_cmd = "2.0.2"
warp = "0.3"
get-port = "4.0.0"
lazy_static = "1.4.0"
bytes = "1.0"
http = "0.2"
