[package]
name = "oha"
version = "0.2.5"
authors = ["hatoo <hato2000@gmail.com>"]
edition = "2018"
description = "Ohayou(おはよう), HTTP load generator, inspired by rakyll/hey with tui animation."
repository = "https://github.com/hatoo/oha"
readme = "README.md"
keywords = ["cli", "load-testing", "performance", "http"]
categories = ["command-line-utilities", "network-programming", "web-programming::http-client", "development-tools::profiling"]
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "2"
structopt = "0.3"
tokio = { version = "0.2", features = ["full"] }
anyhow = "1"
thiserror = "1.0.16"
crossbeam = "0.7"
futures = "0.3"
average = "0.10.4"
float-ord = "0.2.0"
byte-unit = "3.0.3"
tui = { version = "0.9.0", default-features = false, features = ["crossterm"] }
crossterm = "0.17.0"
libc = "0.2.67"
flume = "0.7.0"
humantime = "2.0.0"

hyper = "0.13.4"
http = "0.2"
futures-util = "0.3.4"
native-tls = "0.2.4"
tokio-tls = "0.3.0"
rand = "0.7"
trust-dns-resolver = "0.19.3"
base64 = "0.12.0"


[target.'cfg(unix)'.dependencies]
rlimit = "0.3.0"

[dev-dependencies]
assert_cmd = "1.0.0"
warp = "0.2"
get-port = "1.3.1"
lazy_static = "1.4.0"
bytes = "0.5.4"
http = "0.2"
