[package]
name = "oha"
version = "0.4.4"
authors = ["hatoo <hato2000@gmail.com>"]
edition = "2018"
description = "Ohayou(おはよう), HTTP load generator, inspired by rakyll/hey with tui animation."
repository = "https://github.com/hatoo/oha"
readme = "README.md"
keywords = ["cli", "load-testing", "performance", "http"]
categories = ["command-line-utilities", "network-programming", "web-programming::http-client", "development-tools::profiling"]
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
structopt = "0.3"
tokio = { version = "1.0.1", features = ["full"] }
anyhow = "1.0.38"
thiserror = "1.0.16"
futures = "0.3.12"
average = "0.10.4"
float-ord = "0.2.0"
byte-unit = "4.0.8"
tui = { version = "0.14.0", default-features = false, features = ["crossterm"] }
crossterm = "0.18.0"
libc = "0.2.67"
flume = "0.10"
humantime = "2.0.0"

hyper = { version = "0.14.2", features = ["full"] }
http = "0.2"
native-tls = "0.2.4"
tokio-native-tls = "0.3.0"
rand = "0.8"
trust-dns-resolver = "0.20.0"
base64 = "0.13.0"

[target.'cfg(unix)'.dependencies]
rlimit = "0.5.3"

[dev-dependencies]
assert_cmd = "1.0.0"
warp = "0.3"
get-port = "3"
lazy_static = "1.4.0"
bytes = "1.0"
http = "0.2"
