[package]
name = "oha"
version = "0.4.4"
authors = ["hatoo <hato2000@gmail.com>"]
edition = "2018"
description = "Ohayou(おはよう), HTTP load generator, inspired by rakyll/hey with tui animation."
repository = "https://github.com/hatoo/oha"
readme = "README.md"
keywords = ["cli", "load-testing", "performance", "http"]
categories = ["command-line-utilities", "network-programming", "web-programming::http-client", "development-tools::profiling"]
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
structopt = "0.3"
tokio = { version = "0.3", features = ["full"] }
anyhow = "1"
thiserror = "1.0.16"
futures = "0.3"
average = "0.10.4"
float-ord = "0.2.0"
byte-unit = "4.0.8"
tui = { version = "0.13.0", default-features = false, features = ["crossterm"] }
crossterm = "0.18.0"
libc = "0.2.67"
flume = "0.9"
humantime = "2.0.0"

hyper = { git = "https://github.com/hyperium/hyper.git", features = ["full"] }
http = "0.2"
native-tls = "0.2.4"
tokio-native-tls = "0.2.0"
rand = "0.7"
trust-dns-resolver = { git = "https://github.com/bluejekyll/trust-dns.git", branch = "upgrade-to-tokio-0.3" }
base64 = "0.13.0"

[target.'cfg(unix)'.dependencies]
rlimit = "0.5.3"

[dev-dependencies]
tokio02 = { version = "0.2", features = ["full"], package = "tokio" }
assert_cmd = "1.0.0"
warp = "0.2"
get-port = "3"
lazy_static = "1.4.0"
bytes = "0.5.4"
http = "0.2"

[profile.release]
lto = true
