[package]
name = "oha"
version = "0.1.0"
authors = ["hatoo <hato2000@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { git = "https://github.com/clap-rs/clap/", rev = "19c20f7c00310900ce6667baedfe1190e20eeeab" }
reqwest = { version = "0.10", features = ["json"] }
tokio = { version = "0.2", features = ["full"] }
anyhow = "1"
url = "2"
crossbeam = "0.7"
futures = "0.3"
parse_duration = "2"
average = "0.10.4"
float-ord = "0.2.0"
byte-unit = "3.0.3"
tui = "0.8.0"
termion = "1.5.5"
